### ISSUE TITLE
No JSON Mode implementation.

### ISSUE THREAD

**Issue by etekmen13** [namankhurpia/Easy-open-ai#32]
You don't provide any examples or documentation on how to actually use the new .reponseFormat() extension method for the ChatCompletionRequest class. Looking through the source code doesn't give me any indication of how to use it either.

**Comment by namankhurpia** [comment]
Hi @etekmen13 

kindly look at openai documentation (https://platform.openai.com/docs/api-reference/chat/create) , this repository is an API reference.

Let me know if you find any issues implementing it, you just need to pass it as a string.
