### ISSUE TITLE
Using .topP leads to error

### ISSUE THREAD

**Issue by Dustinhoefer** [namankhurpia/Easy-open-ai#36]
io.github.namankhurpia.Pojo.ChatCompletion.ChatCompletionRequest request = io.github.namankhurpia.Pojo.ChatCompletion.ChatCompletionRequest.builder()
                    .model("gpt-4-turbo-preview")
                    .messages(messages)
                    .temperature(1.0d)
                    .topP(1.0d)
                    .seed(value)
                    .build();
                    
                    
Unsuccessful response with HTTP status code 400 and error body: {
  "error": {
    "message": "Unrecognized request argument supplied: topP",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by Dustinhoefer** [comment]
The parameter is called "top_p"

**Comment by namankhurpia** [comment]
@Dustinhoefer  thanks for mentioning this, this is fixed in PR#37

https://github.com/namankhurpia/Easy-open-ai/pull/37
