### ISSUE TITLE
Invalid body is created for ChatCompletionRequest

### ISSUE THREAD

**Issue by Dimmen** [namankhurpia/Easy-open-ai#38]
**Describe the bug**
The wrong json format is used for the fields maxTokens and responseFormat. 

**To Reproduce**
Unsuccessful response with HTTP status code 400 and error body: {
  "error": {
    "message": "Unrecognized request arguments supplied: maxTokens, responseFormat",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Java Version (please complete the following information):**
 - JDK 21

**Comment by namankhurpia** [comment]
Hi @Dimmen 

can you please provide what you are trying to send for maxToken and responseFormat.
